name: test

# Run on pull requests and on the main branch itself.
on:
  push:
    branches:
      - main
  pull_request:


jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: docker build .
